#!/bin/bash
#Wrapper for package manger

# Running as root breaks this script on yay; AUR wrappers are not supposed to be run as root anyways
if ((EUID == 0)); then
  echo "Do not run as root"
  exit 1
fi

case $1 in
	-search)
		yay -Ss "$2"
		;;
	-upgrade)
		yay -Syu
		;;
	-clean)
		yay -Sc
		yay -Rns $(yay -Qtdq)
		;;
	-install)
		yay -S "$2"
		;;
	-remove)
		yay -Rsn "$2"
		;;
	-mirror-change)
		sudo nano /etc/pacman.d/mirrorlist.pacnew
		sudo rm /etc/pacman.d/mirrorlist
		sudo mv /etc/pacman.d/mirrorlist.pacnew /etc/pacman.d/mirrorlist
		;;
	*)
		echo "-upgrade, -clean, -install (package name), -mirror-change, -remove (package name), -search (search term)"
esac
