#!/bin/bash
#Wrapper for package manger

case $1 in
	-upgrade)
		yay -Syu --aur
		;;
	-clean)
		yay -Sc
		yay -Rns $(yay -Qtdq)
		;;
	-install)
		yay -S "$2"
		;;
	-remove)
		yay -Rsn "$2"
		;;
	-mirror-change)
		sudo nano /etc/pacman.d/mirrorlist.pacnew
		sudo rm /etc/pacman.d/mirrorlist
		sudo mv /etc/pacman.d/mirrorlist.pacnew /etc/pacman.d/mirrorlist
		;;
	*)
		echo "-upgrade, -clean, -install (package name), -mirror-change, -remove (package name)"
esac
